// Image paths
const IMG_HM_LOGO_WHITE = "Logos SHK/Logo Handwerksmanufaktur weiß.png";
const IMG_HM_LOGO_BLACK = "Logos SHK/Logo Handwerksmanufaktur weiß.png";
const IMG_NOAH_FULL = "Logos SHK/img_noah_full.png";
const IMG_NOAH_ROUND = "Logos SHK/img_noah_round.jpeg";
const IMG_GOLDACKER = "Logos SHK/Logo Goldacker weiß.png";
const IMG_KRAMER = "Logos SHK/Logo Kramer Heizungsbau weiß.png";
const IMG_AZEMI = "Logos SHK/Logo Azemi Hausrenovierungen weiß.png";
const IMG_HANNES = "Logos SHK/Logo Hannes Schmidt GmbH Weiß.png";
const IMG_DITSCH = "Logos SHK/Logo Markus Ditsch weiß.png";
const IMG_SENFTLEBEN = "Logos SHK/Logo Senftleben Haustechnik weiß.png";
const IMG_GALLEN = "Logos SHK/Logo Franz Gallenberger weiß.png";
const IMG_BUCHSCHMID = "Logos SHK/Logo Haustechnik Buchschmid weiß.png";
const IMG_KLASS = "Logos SHK/Logo Heizung Sanitär Klaß weiß.png";
const IMG_LANZINGER = "Logos SHK/Logo Lanzinger GmbH weiß.png";
const IMG_LUEDERS = "Logos SHK/Logo Lüders Fliesen weiß.png";
const IMG_FRANTI = "Logos SHK/Logo Franticonstruct weiß.png";
const IMG_STIMPFLE = "Logos SHK/Logo Yannick Stimpfle weiß.png";
const IMG_SUESSMEIER = "Logos SHK/Logo Süßmeier Heizungstechnik weiß.png";
